const appConfig = {

    generator: {
        // 12 makes about 100 case a day hospital.
        absoluteMax: 250,
        defaultMax: 20,
        hourlyPatients: 5000,
        persistConfig: false,
    },

    speedLimit: {
        // See https://www.npmjs.com/package/express-slow-down
        windowMs: 15 * 60 * 1000, // 15 minutes
        delayAfter: 120, // allow 100 requests per 15 minutes, then...
        delayMs: 1500 // begin adding 500ms of delay per request above 100:
    },

    departments: [
        {   active: true,
            department: "CARD" ,
            modalities: ["US", "MR", "DX", "VL"],
            reasons: ["Unstable angina", "Precordial pain",
                "Pleurodynia",  "Intercostal pain",
                "Nonrheumatic aortic (valve) stenosis",
                "Coronary artery aneurysm"
            ]
        },
        {
            active: true,
            department: "ORTHO" ,
            modalities: ["CT", "MR", "US", "DX", "VL"],
            reasons: [
                "20520 Removal of foreign body in muscle or tendon sheath; simple",
                "20525 Removal of foreign body in muscle or tendon sheath; deep or complicated",
                "20670 Removal of implant; superficial, (eg, buried wire, pin or rod) (separate procedure)",
                "20680 Removal of implant; deep (eg, buried wire, pin, screw, metal band, nail, rod or plate)",
                "20920 Fascia lata graft; by stripper",
                "20922 Fascia lata graft; by incision and area exposure, complex or sheet",
                "20924 Tendon graft, from a distance (eg, palmaris, toe extensor, plantaris)",
                "23030 Incision and drainage, shoulder area; deep abscess or hematoma",
                "23031 Incision and drainage, shoulder area; infected bursa",
                "23035 Incision, bone cortex (eg, osteomyelitis or bone abscess), shoulder area",
                "23040 Arthrotomy, glenohumeral joint, including exploration, drainage, or removal of foreign body",
                "23044 Arthrotomy, acromioclavicular, sternoclavicular joint, including exploration, drainage, or removal of",
                "23101 Arthrotomy, acromioclavicular joint or sternoclavicular joint, including biopsy and/or excision of torn",
                "23105 Arthrotomy; glenohumeral joint, with synovectomy, with or without biopsy",
                "23106 Arthrotomy; sternoclavicular joint, with synovectomy, with or without biopsy",
                "23107 Arthrotomy, glenohumeral joint, with joint exploration, with or without removal of loose or foreign",
                "23120 Claviculectomy; partial",
                "23125 Claviculectomy; total",
                "23130 Acromioplasty or acromionectomy, partial, with or without coracoacromial ligament release",
                "23410 Repair of ruptured musculotendinous cuff (eg, rotator cuff) open; acute",
                "23412 Repair of ruptured musculotendinous cuff (eg, rotator cuff) open; chronic",
                "23415 Coracoacromial ligament release, with or without acromioplasty",
                "23420 Reconstruction of complete shoulder (rotator) cuff avulsion, chronic (includes acromioplasty)",
                "23430 Tenodesis of long tendon of biceps",
                "23440 Resection or transplantation of long tendon of biceps",
                "23450 Capsulorrhaphy, anterior; Putti-Platt procedure or Magnuson type operation",
                "23455 Capsulorrhaphy, anterior; with labral repair (eg, Bankart procedure)",
                "23460 Capsulorrhaphy, anterior, any type; with bone block",
                "23462 Capsulorrhaphy, anterior, any type; with coracoid process transfer",
                "23465 Capsulorrhaphy, glenohumeral joint, posterior, with or without bone block",
                "23466 Capsulorrhaphy, glenohumeral joint, any type multi-directional instability",
                "23485 Osteotomy, clavicle, with or without internal fixation; with bone graft for nonunion or malunion (includes obtaining graft and/or necessary fixation)",
                "23500 Closed treatment of clavicular fracture; without manipulation",
                "23505 Closed treatment of clavicular fracture; with manipulation",
                "23515 Open treatment of clavicular fracture, with or without internal or external fixation",
                "23520 Closed treatment of sternoclavicular dislocation; without manipulation",
                "23525 Closed treatment of sternoclavicular dislocation; with manipulation",
                "23530 Open treatment of sternoclavicular dislocation, acute or chronic",
                "23532 Open treatment of sternoclavicular dislocation, acute or chronic; with fascial graft (includes obtaining",
                "23540 Closed treatment of acromioclavicular dislocation; without manipulation",
                "23545 Closed treatment of acromioclavicular dislocation; with manipulation",
                "23550 Open treatment of acromioclavicular dislocation, acute or chronic;",
                "23552 Open treatment of acromioclavicular dislocation, acute or chronic; with fascial graft (includes",
                "23570 Closed treatment of scapular fracture; without manipulation",
                "23615 Open treatment of proximal humeral (surgical or anatomical neck) fracture, with or without internal or external fixation, with or without repair of tuberosity(s);",
                "23650 Closed treatment of shoulder dislocation, with manipulation; without anesthesia",
                "23655 Closed treatment of shoulder dislocation, with manipulation; requiring anesthesia",
                "23660 Open treatment of acute shoulder dislocation",
                "23665 Closed treatment of shoulder dislocation, with fracture of greater humeral tuberosity, with",
                "23670 Open treatment of shoulder dislocation, with fracture of greater humeral tuberosity, with or without",
                "23675 Closed treatment of shoulder dislocation, with surgical or anatomical neck fracture, with",
                "23700 Manipulation under anesthesia, shoulder joint, including application of fixation apparatus (dislocation",
                "24006 Arthrotomy of the elbow, with capsular excision for capsular release (separate procedure)",
                "24101 Arthrotomy, elbow; with joint exploration, with or without biopsy, with or without removal of loose or",
                "24200 Removal of foreign body, upper arm or elbow area; subcutaneous",
                "24201 Removal of foreign body, upper arm or elbow area; deep (subfascial or intramuscular)",
                "24301 Muscle or tendon transfer, any type, upper arm or elbow, single (excluding 24320-24331)",
                "24305 Tendon lengthening, upper arm or elbow, each tendon",
                "24310 Tenotomy, open, elbow to shoulder, each tendon",
                "24320 Tenoplasty, with muscle transfer, with or without free graft, elbow to shoulder, single (Seddon-",
                "24332 Tenolysis, triceps",
                "24340 Tenodesis of biceps tendon at elbow (separate procedure)",
                "24341 Repair, tendon or muscle, upper arm or elbow, each tendon or muscle, primary or secondary",
                "24342 Reinsertion of ruptured biceps or triceps tendon, distal, with or without tendon graft",
                "24343 Repair lateral collateral ligament, elbow, with local tissue",
                "24344 Reconstruction lateral collateral ligament, elbow, with tendon graft (includes harvesting of graft)",
                "24345 Repair medial collateral ligament, elbow, with local tissue",
                "24346 Reconstruction medial collateral ligament, elbow, with tendon graft (includes harvesting of graft)",
                "24350 Fasciotomy, lateral or medial (eg, tennis elbow or epicondylitis);",
                "24351 Fasciotomy, lateral or medial (eg, tennis elbow or epicondylitis); with extensor origin detachment",
                "24352 Fasciotomy, lateral or medial (eg, tennis elbow or epicondylitis); with annular ligament resection",
                "24354 Fasciotomy, lateral or medial (eg, tennis elbow or epicondylitis); with stripping",
                "24356 Fasciotomy, lateral or medial (eg, tennis elbow or epicondylitis); with partial ostectomy",
                "24500 Closed treatment of humeral shaft fracture; without manipulation",
                "24505 Closed treatment of humeral shaft fracture; with manipulation, with or without skeletal traction",
                "24515 Open treatment of humeral shaft fracture with plate/screws, with or without cerclage",
                "24516 Treatment of humeral shaft fracture, with insertion of intramedullary implant, with or without cerclage",
                "24530 Closed treatment of supracondylar or transcondylar humeral fracture, with or without intercondylar extension; without manipulation",
                "24535 Closed treatment of supracondylar or transcondylar humeral fracture, with or without intercondylar extension; with manipulation, with or without skin or skeletal traction",
                "24538 Percutaneous skeletal fixation of supracondylar or transcondylar humeral fracture, with or without",
                "24545 Open treatment of humeral supracondylar or transcondylar fracture, with or without internal or external fixation; without intercondylar extension",
                "24546 Open treatment of humeral supracondylar or transcondylar fracture, with or without internal or external fixation; with intercondylar extension",
                "24560 Closed treatment of humeral epicondylar fracture, medial or lateral; without manipulation",
                "24565 Closed treatment of humeral epicondylar fracture, medial or lateral; with manipulation",
                "24566 Percutaneous skeletal fixation of humeral epicondylar fracture, medial or lateral, with manipulation",
                "24575 Open treatment of humeral epicondylar fracture, medial or lateral, with or without internal or external",
                "24576 Closed treatment of humeral condylar fracture, medial or lateral; without manipulation",
                "24577 Closed treatment of humeral condylar fracture, medial or lateral; with manipulation",
                "24579 Open treatment of humeral condylar fracture, medial or lateral, with or without internal or external",
                "24582 Percutaneous skeletal fixation of humeral condylar fracture, medial or lateral, with manipulation",
                "24586 Open treatment of periarticular fracture and/or dislocation of the elbow (fracture distal humerus and proximal ulna and/or proximal radius);",
                "24600 Treatment of closed elbow dislocation; without anesthesia",
                "24605 Treatment of closed elbow dislocation; requiring anesthesia",
                "24615 Open treatment of acute or chronic elbow dislocation",
                "24620 Closed treatment of Monteggia type of fracture dislocation at elbow (fracture proximal end of ulna with dislocation of radial head), with manipulation",
                "24635 Open treatment of Monteggia type of fracture dislocation at elbow (fracture proximal end of ulna with dislocation of radial head), with or without internal or external fixation",
                "24640 Closed treatment of radial head subluxation in child, nursemaid elbow, with manipulation",
                "24650 Closed treatment of radial head or neck fracture; without manipulation",
                "24655 Closed treatment of radial head or neck fracture; with manipulation",
                "24665 Open treatment of radial head or neck fracture, with or without internal fixation or radial head",
                "24666 Open treatment of radial head or neck fracture, with or without internal fixation or radial head excision; with radial head prosthetic replacement",
                "24670 Closed treatment of ulnar fracture, proximal end (olecranon process); without manipulation",
                "24675 Closed treatment of ulnar fracture, proximal end (olecranon process); with manipulation",
                "24685 Open treatment of ulnar fracture proximal end (olecranon process), with or without internal or",
                "25020 Decompression fasciotomy, forearm and/or wrist, flexor OR extensor compartment; without debridement of nonviable muscle and/or nerve",
                "25023 Decompression fasciotomy, forearm and/or wrist, flexor OR extensor compartment; with debridement of nonviable muscle and/or nerve",
                "25024 Decompression fasciotomy, forearm and/or wrist, flexor AND extensor compartment; without debridement of nonviable muscle and/or nerve",
                "25025 Decompression fasciotomy, forearm and/or wrist, flexor AND extensor compartment; with debridement of nonviable muscle and/or nerve",
                "25028 Incision and drainage, forearm and/or wrist; deep abscess or hematoma",
                "25031 Incision and drainage, forearm and/or wrist; bursa",
                "25035 Incision, deep, bone cortex, forearm and/or wrist (eg, osteomyelitis or bone abscess)",
                "25040 Arthrotomy, radiocarpal or midcarpal joint, with exploration, drainage, or removal of foreign body",
                "25260 Repair, tendon or muscle, flexor, forearm and/or wrist; primary, single, each tendon or muscle",
                "25263 Repair, tendon or muscle, flexor, forearm and/or wrist; secondary, single, each tendon or muscle",
                "25265 Repair, tendon or muscle, flexor, forearm and/or wrist; secondary, with free graft (includes obtaining graft), each tendon or muscle",
                "25270 Repair, tendon or muscle, extensor, forearm and/or wrist; primary, single, each tendon or muscle",
                "25272 Repair, tendon or muscle, extensor, forearm and/or wrist; secondary, single, each tendon or muscle",
                "25274 Repair, tendon or muscle, extensor, forearm and/or wrist; secondary, with free graft (includes obtaining graft), each tendon or muscle",
                "25275 Repair, tendon sheath, extensor, forearm and/or wrist, with free graft (includes obtaining graft) (eg, for extensor carpi ulnaris subluxation)",
                "25320 Capsulorrhaphy or reconstruction, wrist, open (eg, capsulodesis, ligament repair, tendon transfer or graft) (includes synovectomy, capsulotomy and open reduction) for carpal instability",
                "25337 Reconstruction for stabilization of unstable distal ulna or distal radioulnar joint, secondary by soft tissue stabilization (eg, tendon transfer, tendon graft or weave, or tenodesis) with or without open",
                "25430 Insertion of vascular pedicle into carpal bone (eg, Hori procedure)",
                "25431 Repair of nonunion of carpal bone (excluding carpal scaphoid (navicular)) (includes obtaining graft and necessary fixation), each bone",
                "25440 Repair of nonunion, scaphoid carpal (navicular) bone, with or without radial styloidectomy (includes obtaining graft and necessary fixation)",
                "25500 Closed treatment of radial shaft fracture; without manipulation",
                "25505 Closed treatment of radial shaft fracture; with manipulation",
                "25515 Open treatment of radial shaft fracture, with or without internal or external fixation",
                "25520 Closed treatment of radial shaft fracture and closed treatment of dislocation of distal radioulnar joint (Galeazzi fracture/dislocation)",
                "25525 Open treatment of radial shaft fracture, with internal and/ or external fixation and closed treatment of dislocation of distal radioulnar joint (Galeazzi fracture/dislocation), with or without percutaneous",
                "25526 Open treatment of radial shaft fracture, with internal and/or external fixation and open treatment, with or without internal or external fixation of distal radioulnar joint (Galeazzi fracture/dislocation),",
                "25530 Closed treatment of ulnar shaft fracture; without manipulation",
                "25535 Closed treatment of ulnar shaft fracture; with manipulation",
                "25545 Open treatment of ulnar shaft fracture, with or without internal or external fixation",
                "25560 Closed treatment of radial and ulnar shaft fractures; without manipulation",
                "25565 Closed treatment of radial and ulnar shaft fractures; with manipulation",
                "25574 Open treatment of radial AND ulnar shaft fractures, with internal or external fixation; of radius OR",
                "25575 Open treatment of radial AND ulnar shaft fractures, with internal or external fixation; of radius AND",
                "25600 Closed treatment of distal radial fracture (eg, Colles or Smith type) or epiphyseal separation, with or without fracture of ulnar styloid; without manipulation",
                "25605 Closed treatment of distal radial fracture (eg, Colles or Smith type) or epiphyseal separation, with or without fracture of ulnar styloid; with manipulation",
                "25606 Percutaneous skeletal fixation of distal radial fracture or epiphyseal separation",
                "25607 Open treatment of distal radial extra-articular fracture or epiphyseal separation, with internal fixation",
                "25608 Open treatment of distal radial intra-articular fracture or epiphyseal separation; with internal fixation",
                "25609 With internal fixation of 3 or more fragments",
                "25622 Closed treatment of carpal scaphoid (navicular) fracture; without manipulation",
                "25624 Closed treatment of carpal scaphoid (navicular) fracture; with manipulation",
                "25628 Open treatment of carpal scaphoid (navicular) fracture, with or without internal or external fixation",
                "25630 Closed treatment of carpal bone fracture (excluding carpal scaphoid (navicular)); without",
                "25635 Closed treatment of carpal bone fracture (excluding carpal scaphoid (navicular)); with manipulation,",
                "25645 Open treatment of carpal bone fracture (other than carpal scaphoid (navicular)), each bone",
                "25650 Closed treatment of ulnar styloid fracture",
                "25651 Percutaneous skeletal fixation of ulnar styloid fracture",
                "25652 Open treatment of ulnar styloid fracture",
                "25660 Closed treatment of radiocarpal or intercarpal dislocation, one or more bones, with manipulation",
                "25670 Open treatment of radiocarpal or intercarpal dislocation, one or more bones",
                "25671 Percutaneous skeletal fixation of distal radioulnar dislocation",
                "25675 Closed treatment of distal radioulnar dislocation with manipulation",
                "25676 Open treatment of distal radioulnar dislocation, acute or chronic",
                "25680 Closed treatment of trans-scaphoperilunar type of fracture dislocation, with manipulation",
                "25685 Open treatment of trans-scaphoperilunar type of fracture dislocation",
                "25690 Closed treatment of lunate dislocation, with manipulation",
                "25695 Open treatment of lunate dislocation",
                "26010 Drainage of finger abscess; simple",
                "26011 Drainage of finger abscess; complicated (eg, felon)",
                "26020 Drainage of tendon sheath, digit and/or palm, each",
                "26025 Drainage of palmar bursa; single, bursa",
                "26030 Drainage of palmar bursa; multiple bursa",
                "26037 Decompressive fasciotomy, hand (excludes 26035)",
                "26055 Tendon sheath incision (eg, for trigger finger)",
                "26060 Tenotomy, percutaneous, single, each digit",
                "26070 Arthrotomy, with exploration, drainage, or removal of loose or foreign body; carpometacarpal joint",
                "26075 Arthrotomy, with exploration, drainage, or removal of loose or foreign body; metacarpophalangeal",
                "26080 Arthrotomy, with exploration, drainage, or removal of loose or foreign body; interphalangeal joint,",
                "26185 Sesamoidectomy, thumb or finger (separate procedure)",
                "26320 Removal of implant from finger or hand",
                "26356 Repair or advancement, flexor tendon, in zone 2 digital flexor tendon sheath (eg, no man's land); primary, without free graft, each tendon",
                "26357 Repair or advancement, flexor tendon, in zone 2 digital flexor tendon sheath (eg, no man's land); secondary, without free graft, each tendon",
                "26358 Repair or advancement, flexor tendon, in zone 2 digital flexor tendon sheath (eg, no man's land); secondary, with free graft (includes obtaining graft), each tendon",
                "26370 Repair or advancement of profundus tendon, with intact superficialis tendon; primary, each tendon",
                "26372 Repair or advancement of profundus tendon, with intact superficialis tendon; secondary with free graft (includes obtaining graft), each tendon",
                "26373 Repair or advancement of profundus tendon, with intact superficialis tendon; secondary without free",
                "26426 Repair of extensor tendon, central slip, secondary (eg, boutonniere deformity); using local tissue(s), including lateral band(s), each finger",
                "26428 Repair of extensor tendon, central slip, secondary (eg, boutonniere deformity); with free graft (includes obtaining graft), each finger",
                "26432 Closed treatment of distal extensor tendon insertion, with or without percutaneous pinning (eg,",
                "26433 Repair of extensor tendon, distal insertion, primary or secondary; without graft (eg, mallet finger)",
                "26434 Repair of extensor tendon, distal insertion, primary or secondary; with free graft (includes obtaining",
                "26437 Realignment of extensor tendon, hand, each tendon",
                "26500 Reconstruction of tendon pulley, each tendon; with local tissues (separate procedure)",
                "26502 Reconstruction of tendon pulley, each tendon; with tendon or fascial graft (includes obtaining graft)",
                "26540 Repair of collateral ligament, metacarpophalangeal or interphalangeal joint",
                "26541 Reconstruction, collateral ligament, metacarpophalangeal joint, single; with tendon or fascial graft",
                "26542 Reconstruction, collateral ligament, metacarpophalangeal joint, single; with local tissue (eg,",
                "26545 Reconstruction, collateral ligament, interphalangeal joint, single, including graft, each joint",
                "26548 Repair and reconstruction, finger, volar plate, interphalangeal joint",
                "26600 Closed treatment of metacarpal fracture, single; without manipulation, each bone",
                "26605 Closed treatment of metacarpal fracture, single; with manipulation, each bone",
                "26607 Closed treatment of metacarpal fracture, with manipulation, with external fixation, each bone",
                "26608 Percutaneous skeletal fixation of metacarpal fracture, each bone",
                "26615 Open treatment of metacarpal fracture, single, with or without internal or external fixation, each bone",
                "26641 Closed treatment of carpometacarpal dislocation, thumb, with manipulation",
                "26645 Closed treatment of carpometacarpal fracture dislocation, thumb (Bennett fracture), with",
                "26650 Percutaneous skeletal fixation of carpometacarpal fracture dislocation, thumb (Bennett fracture), with manipulation, with or without external fixation",
                "26665 Open treatment of carpometacarpal fracture dislocation, thumb (Bennett fracture), with or without",
                "26670 Closed treatment of carpometacarpal dislocation, other than thumb, with manipulation, each joint;",
                "26675 Closed treatment of carpometacarpal dislocation, other than thumb, with manipulation, each joint;",
                "26676 Percutaneous skeletal fixation of carpometacarpal dislocation, other than thumb, with manipulation,",
                "26685 Open treatment of carpometacarpal dislocation, other than thumb; with or without internal or",
                "26686 Open treatment of carpometacarpal dislocation, other than thumb; complex, multiple or delayed",
                "26700 Closed treatment of metacarpophalangeal dislocation, single, with manipulation; without anesthesia",
                "26705 Closed treatment of metacarpophalangeal dislocation, single, with manipulation; requiring",
                "26706 Percutaneous skeletal fixation of metacarpophalangeal dislocation, single, with manipulation",
                "26715 Open treatment of metacarpophalangeal dislocation, single, with or without internal or external",
                "26720 Closed treatment of phalangeal shaft fracture, proximal or middle phalanx, finger or thumb; without",
                "26725 Closed treatment of phalangeal shaft fracture, proximal or middle phalanx, finger or thumb; with manipulation, with or without skin or skeletal traction, each",
                "26727 Percutaneous skeletal fixation of unstable phalangeal shaft fracture, proximal or middle phalanx, finger or thumb, with manipulation, each",
                "26735 Open treatment of phalangeal shaft fracture, proximal or middle phalanx, finger or thumb, with or without internal or external fixation, each",
                "26740 Closed treatment of articular fracture, involving metacarpophalangeal or interphalangeal joint;",
                "26742 Closed treatment of articular fracture, involving metacarpophalangeal or interphalangeal joint; with",
                "26746 Open treatment of articular fracture, involving metacarpophalangeal or interphalangeal joint, with or without internal or external fixation, each",
                "26750 Closed treatment of distal phalangeal fracture, finger or thumb; without manipulation, each",
                "26755 Closed treatment of distal phalangeal fracture, finger or thumb; with manipulation, each",
                "26756 Percutaneous skeletal fixation of distal phalangeal fracture, finger or thumb, each",
                "26765 Open treatment of distal phalangeal fracture, finger or thumb, with or without internal or external",
                "26770 Closed treatment of interphalangeal joint dislocation, single, with manipulation; without anesthesia",
                "26775 Closed treatment of interphalangeal joint dislocation, single, with manipulation; requiring anesthesia",
                "26776 Percutaneous skeletal fixation of interphalangeal joint dislocation, single, with manipulation",
                "26785 Open treatment of interphalangeal joint dislocation, with or without internal or external fixation, single",
                "26990 Incision and drainage, pelvis or hip joint area; deep abscess or hematoma",
                "26991 Incision and drainage, pelvis or hip joint area; infected bursa",
                "27086 Removal of foreign body, pelvis or hip; subcutaneous tissue",
                "27087 Removal of foreign body, pelvis or hip; deep (subfascial or intramuscular)",
                "27230 Closed treatment of femoral fracture, proximal end, neck; without manipulation",
                "27232 Closed treatment of femoral fracture, proximal end, neck; with manipulation, with or without skeletal",
                "27235 Percutaneous skeletal fixation of femoral fracture, proximal end, neck",
                "27236 Open treatment of femoral fracture, proximal end, neck, internal fixation or prosthetic replacement",
                "27238 Closed treatment of intertrochanteric, pertrochanteric, or subtrochanteric femoral fracture; without",
                "27240 Closed treatment of intertrochanteric, pertrochanteric, or subtrochanteric femoral fracture; with manipulation, with or without skin or skeletal traction",
                "27244 Treatment of intertrochanteric, pertrochanteric, or subtrochanteric femoral fracture; with plate/screw type implant, with or without cerclage",
                "27245 Treatment of intertrochanteric, pertrochanteric, or subtrochanteric femoral fracture; with intramedullary implant, with or without interlocking screws and/or cerclage",
                "27246 Closed treatment of greater trochanteric fracture, without manipulation",
                "27248 Open treatment of greater trochanteric fracture, with or without internal or external fixation",
                "27250 Closed treatment of hip dislocation, traumatic; without anesthesia",
                "27252 Closed treatment of hip dislocation, traumatic; requiring anesthesia",
                "27253 Open treatment of hip dislocation, traumatic, without internal fixation",
                "27254 Open treatment of hip dislocation, traumatic, with acetabular wall and femoral head fracture, with or without internal or external fixation",
                "27256 Treatment of spontaneous hip dislocation (developmental, including congenital or pathological), by abduction, splint or traction; without anesthesia, without manipulation",
                "27257 Treatment of spontaneous hip dislocation (developmental, including congenital or pathological), by abduction, splint or traction; with manipulation, requiring anesthesia",
                "27258 Open treatment of spontaneous hip dislocation (developmental, including congenital or pathological), replacement of femoral head in acetabulum (including tenotomy, etc);",
                "27259 Open treatment of spontaneous hip dislocation (developmental, including congenital or pathological), replacement of femoral head in acetabulum (including tenotomy, etc); with femoral",
                "27265 Closed treatment of post hip arthroplasty dislocation; without anesthesia",
                "27266 Closed treatment of post hip arthroplasty dislocation; requiring regional or general anesthesia",
                "27301 Incision and drainage, deep abscess, bursa, or hematoma, thigh or knee region",
                "27303 Incision, deep, with opening of bone cortex, femur or knee (eg, osteomyelitis or bone abscess)",
                "27305 Fasciotomy, iliotibial (tenotomy), open",
                "27306 Tenotomy, percutaneous, adductor or hamstring; single tendon (separate procedure)",
                "27307 Tenotomy, percutaneous, adductor or hamstring; multiple tendons",
                "27310 Arthrotomy, knee, with exploration, drainage, or removal of foreign body (eg, infection)",
                "27330 Arthrotomy, knee; with synovial biopsy only",
                "27331 Arthrotomy, knee; including joint exploration, biopsy, or removal of loose or foreign bodies",
                "27332 Arthrotomy, with excision of semilunar cartilage (meniscectomy) knee; medial OR lateral",
                "27333 Arthrotomy, with excision of semilunar cartilage (meniscectomy) knee; medial AND lateral",
                "27334 Arthrotomy, with synovectomy, knee; anterior OR posterior",
                "27335 Arthrotomy, with synovectomy, knee; anterior AND posterior including popliteal area",
                "27340 excision, prepatellar bursa",
                "27345 Excision of synovial cyst of popliteal space (eg, Baker's cyst)",
                "27347 Excision of lesion of meniscus or capsule (eg, cyst, ganglion), knee",
                "27350 Patellectomy or hemipatellectomy",
                "27355 Excision or curettage of bone cyst or benign tumor of femur;",
                "27356 Excision or curettage of bone cyst or benign tumor of femur; with allograft",
                "27357 Excision or curettage of bone cyst or benign tumor of femur; with autograft (includes obtaining graft)",
                "27358 Excision or curettage of bone cyst or benign tumor of femur; with internal fixation (List in addition to code for primary procedure)",
                "27360 Partial excision (craterization, saucerization, or diaphysectomy) bone, femur, proximal tibia and/or fibula (eg, osteomyelitis or bone abscess)",
                "27372 Removal of foreign body, deep, thigh region or knee area",
                "27380 Suture of infrapatellar tendon; primary",
                "27381 Suture of infrapatellar tendon; secondary reconstruction, including fascial or tendon graft",
                "27385 Suture of quadriceps or hamstring muscle rupture; primary",
                "27386 Suture of quadriceps or hamstring muscle rupture; secondary reconstruction, including fascial or",
                "27390 Tenotomy, open, hamstring, knee to hip; single tendon",
                "27391 Tenotomy, open, hamstring, knee to hip; multiple tendons, one leg",
                "27392 Tenotomy, open, hamstring, knee to hip; multiple tendons, bilateral",
                "27393 Lengthening of hamstring tendon; single tendon",
                "27394 Lengthening of hamstring tendon; multiple tendons, one leg",
                "27395 Lengthening of hamstring tendon; multiple tendons, bilateral",
                "27396 Transplant, hamstring tendon to patella; single tendon",
                "27397 Transplant, hamstring tendon to patella; multiple tendons",
                "27400 Transfer, tendon or muscle, hamstrings to femur (eg, Egger's type procedure)",
                "27403 Arthrotomy with meniscus repair, knee",
                "27405 Repair, primary, torn ligament and/or capsule, knee; collateral",
                "27407 Repair, primary, torn ligament and/or capsule, knee; cruciate",
                "27409 Repair, primary, torn ligament and/or capsule, knee; collateral and cruciate ligaments",
                "27412 Autologous chondrocyte implantation, knee",
                "27415 Osteochondral allograft, knee, open",
                "27418 Anterior tibial tubercleplasty (eg, Maquet type procedure)",
                "27420 Reconstruction of dislocating patella; (eg, Hauser type procedure)",
                "27422 Reconstruction of dislocating patella; with extensor realignment and/or muscle advancement or release (eg, Campbell, Goldwaite type procedure)",
                "27424 Reconstruction of dislocating patella; with patellectomy",
                "27425 Lateral retinacular release, open",
                "27427 Ligamentous reconstruction (augmentation), knee; extra-articular",
                "27428 Ligamentous reconstruction (augmentation), knee; intra-articular (open)",
                "27429 Ligamentous reconstruction (augmentation), knee; intra-articular (open) and extra-articular",
                "27430 Quadricepsplasty (eg, Bennett or Thompson type)",
                "27435 Capsulotomy, posterior capsular release, knee",
                "27448 Osteotomy, femur, shaft or supracondylar; without fixation",
                "27450 Osteotomy, femur, shaft or supracondylar; with fixation",
                "27455 Osteotomy, proximal tibia, including fibular excision or osteotomy (includes correction of genu varus (bowleg) or genu valgus (knock-knee)); before epiphyseal closure",
                "27457 Osteotomy, proximal tibia, including fibular excision or osteotomy (includes correction of genu varus (bowleg) or genu valgus (knock-knee)); after epiphyseal closure",
                "27496 Decompression fasciotomy, thigh and/or knee, one compartment (flexor or extensor or adductor);",
                "27497 Decompression fasciotomy, thigh and/or knee, one compartment (flexor or extensor or adductor); with debridement of nonviable muscle and/or nerve",
                "27498 Decompression fasciotomy, thigh and/or knee, multiple compartments;",
                "27499 Decompression fasciotomy, thigh and/or knee, multiple compartments; with debridement of",
                "27500 Closed treatment of femoral shaft fracture, without manipulation",
                "27501 Closed treatment of supracondylar or transcondylar femoral fracture with or without intercondylar",
                "27502 Closed treatment of femoral shaft fracture, with manipulation, with or without skin or skeletal traction",
                "27503 Closed treatment of supracondylar or transcondylar femoral fracture with or without intercondylar extension, with manipulation, with or without skin or skeletal traction",
                "27506 Open treatment of femoral shaft fracture, with or without external fixation, with insertion of intramedullary implant, with or without cerclage and/or locking screws",
                "27507 Open treatment of femoral shaft fracture with plate/screws, with or without cerclage",
                "27508 Closed treatment of femoral fracture, distal end, medial or lateral condyle, without manipulation",
                "27509 Percutaneous skeletal fixation of femoral fracture, distal end, medial or lateral condyle, or supracondylar or transcondylar, with or without intercondylar extension, or distal femoral epiphyseal",
                "27510 Closed treatment of femoral fracture, distal end, medial or lateral condyle, with manipulation",
                "27511 Open treatment of femoral supracondylar or transcondylar fracture without intercondylar extension, with or without internal or external fixation",
                "27513 Open treatment of femoral supracondylar or transcondylar fracture with intercondylar extension, with or without internal or external fixation",
                "27514 Open treatment of femoral fracture, distal end, medial or lateral condyle, with or without internal or",
                "27516 Closed treatment of distal femoral epiphyseal separation; without manipulation",
                "27517 Closed treatment of distal femoral epiphyseal separation; with manipulation, with or without skin or",
                "27519 Open treatment of distal femoral epiphyseal separation, with or without internal or external fixation",
                "27520 Closed treatment of patellar fracture, without manipulation",
                "27524 Open treatment of patellar fracture, with internal fixation and/or partial or complete patellectomy and",
                "27530 Closed treatment of tibial fracture, proximal (plateau); without manipulation",
                "27532 Closed treatment of tibial fracture, proximal (plateau); with or without manipulation, with skeletal",
                "27535 Open treatment of tibial fracture, proximal (plateau); unicondylar, with or without internal or external",
                "27536 Open treatment of tibial fracture, proximal (plateau); bicondylar, with or without internal fixation",
                "27538 Closed treatment of intercondylar spine(s) and/or tuberosity fracture(s) of knee, with or without",
                "27540 Open treatment of intercondylar spine(s) and/or tuberosity fracture(s) of the knee, with or without",
                "27550 Closed treatment of knee dislocation; without anesthesia",
                "27552 Closed treatment of knee dislocation; requiring anesthesia",
                "27556 Open treatment of knee dislocation, with or without internal or external fixation; without primary ligamentous repair or augmentation/reconstruction",
                "27557 Open treatment of knee dislocation, with or without internal or external fixation; with primary",
                "27558 Open treatment of knee dislocation, with or without internal or external fixation; with primary ligamentous repair, with augmentation/reconstruction",
                "27560 Closed treatment of patellar dislocation; without anesthesia",
                "27562 Closed treatment of patellar dislocation; requiring anesthesia",
                "27566 Open treatment of patellar dislocation, with or without partial or total patellectomy",
                "27570 Manipulation of knee joint under general anesthesia (includes application of traction or other fixation",
                "27600 Decompression fasciotomy, leg; anterior and/or lateral compartments only",
                "27601 Decompression fasciotomy, leg; posterior compartment(s) only",
                "27602 Decompression fasciotomy, leg; anterior and/or lateral, and posterior compartment(s)",
                "27603 Incision and drainage, leg or ankle; deep abscess or hematoma",
                "27604 Incision and drainage, leg or ankle; infected bursa",
                "27605 Tenotomy, percutaneous, Achilles tendon (separate procedure); local anesthesia",
                "27606 Tenotomy, percutaneous, Achilles tendon (separate procedure); general anesthesia",
                "27607 Incision (eg, osteomyelitis or bone abscess), leg or ankle",
                "27610 Arthrotomy, ankle, including exploration, drainage, or removal of foreign body",
                "27612 Arthrotomy, posterior capsular release, ankle, with or without Achilles tendon lengthening",
                "27620 Arthrotomy, ankle, with joint exploration, with or without biopsy, with or without removal of loose or",
                "27625 Arthrotomy, with synovectomy, ankle;",
                "27626 Arthrotomy, with synovectomy, ankle; including tenosynovectomy",
                "27630 Excision of lesion of tendon sheath or capsule (eg, cyst or ganglion), leg and/or ankle",
                "27650 Repair, primary, open or percutaneous, ruptured Achilles tendon;",
                "27652 Repair, primary, open or percutaneous, ruptured Achilles tendon; with graft (includes obtaining graft)",
                "27654 Repair, secondary, Achilles tendon, with or without graft",
                "27656 Repair, fascial defect of leg",
                "27658 Repair, flexor tendon, leg; primary, without graft, each tendon",
                "27659 Repair, flexor tendon, leg; secondary, with or without graft, each tendon",
                "27664 Repair, extensor tendon, leg; primary, without graft, each tendon",
                "27665 Repair, extensor tendon, leg; secondary, with or without graft, each tendon",
                "27675 Repair, dislocating peroneal tendons; without fibular osteotomy",
                "27676 Repair, dislocating peroneal tendons; with fibular osteotomy",
                "27680 Tenolysis, flexor or extensor tendon, leg and/or ankle; single, each tendon",
                "27681 Tenolysis, flexor or extensor tendon, leg and/or ankle; multiple tendons (through separate",
                "27695 Repair, primary, disrupted ligament, ankle; collateral",
                "27696 Repair, primary, disrupted ligament, ankle; both collateral ligaments",
                "27698 Repair, secondary, disrupted ligament, ankle, collateral (eg, Watson-Jones procedure)",
                "27705 Osteotomy; tibia",
                "27707 Osteotomy; fibula",
                "27709 Osteotomy; tibia and fibula",
                "27750 Closed treatment of tibial shaft fracture (with or without fibular fracture); without manipulation",
                "27752 Closed treatment of tibial shaft fracture (with or without fibular fracture); with manipulation, with or",
                "27756 Percutaneous skeletal fixation of tibial shaft fracture (with or without fibular fracture) (eg, pins or",
                "27758 Open treatment of tibial shaft fracture, (with or without fibular fracture) with plate/screws, with or",
                "27759 Treatment of tibial shaft fracture (with or without fibular fracture) by intramedullary implant, with or without interlocking screws and/or cerclage",
                "27760 Closed treatment of medial malleolus fracture; without manipulation",
                "27762 Closed treatment of medial malleolus fracture; with manipulation, with or without skin or skeletal",
                "27766 Open treatment of medial malleolus fracture, with or without internal or external fixation",
                "27780 Closed treatment of proximal fibula or shaft fracture; without manipulation",
                "27781 Closed treatment of proximal fibula or shaft fracture; with manipulation",
                "27784 Open treatment of proximal fibula or shaft fracture, with or without internal or external fixation",
                "27786 Closed treatment of distal fibular fracture (lateral malleolus); without manipulation",
                "27788 Closed treatment of distal fibular fracture (lateral malleolus); with manipulation",
                "27792 Open treatment of distal fibular fracture (lateral malleolus), with or without internal or external",
                "27808 Closed treatment of bimalleolar ankle fracture, (including Potts); without manipulation",
                "27810 Closed treatment of bimalleolar ankle fracture, (including Potts); with manipulation",
                "27814 Open treatment of bimalleolar ankle fracture, with or without internal or external fixation",
                "27816 Closed treatment of trimalleolar ankle fracture; without manipulation",
                "27818 Closed treatment of trimalleolar ankle fracture; with manipulation",
                "27822 Open treatment of trimalleolar ankle fracture, with or without internal or external fixation, medial and/or lateral malleolus; without fixation of posterior lip",
                "27823 Open treatment of trimalleolar ankle fracture, with or without internal or external fixation, medial and/or lateral malleolus; with fixation of posterior lip",
                "27824 Closed treatment of fracture of weight bearing articular portion of distal tibia (eg, pilon or tibial plafond), with or without anesthesia; without manipulation",
                "27825 Closed treatment of fracture of weight bearing articular portion of distal tibia (eg, pilon or tibial plafond), with or without anesthesia; with skeletal traction and/or requiring manipulation",
                "27826 Open treatment of fracture of weight bearing articular surface/portion of distal tibia (eg, pilon or tibial plafond), with internal or external fixation; of fibula only",
                "27827 Open treatment of fracture of weight bearing articular surface/portion of distal tibia (eg, pilon or tibial plafond), with internal or external fixation; of tibia only",
                "27828 Open treatment of fracture of weight bearing articular surface/portion of distal tibia (eg, pilon or tibial plafond), with internal or external fixation; of both tibia and fibula",
                "27829 Open treatment of distal tibiofibular joint (syndesmosis) disruption, with or without internal or",
                "27830 Closed treatment of proximal tibiofibular joint dislocation; without anesthesia",
                "27831 Closed treatment of proximal tibiofibular joint dislocation; requiring anesthesia",
                "27832 Open treatment of proximal tibiofibular joint dislocation, with or without internal or external fixation, or with excision of proximal fibula",
                "27840 Closed treatment of ankle dislocation; without anesthesia",
                "27842 Closed treatment of ankle dislocation; requiring anesthesia, with or without percutaneous skeletal",
                "27846 Open treatment of ankle dislocation, with or without percutaneous skeletal fixation; without repair or",
                "27848 Open treatment of ankle dislocation, with or without percutaneous skeletal fixation; with repair or",
                "27860 Manipulation of ankle under general anesthesia (includes application of traction or other fixation",
                "27892 Decompression fasciotomy, leg; anterior and/or lateral compartments only, with debridement of",
                "27893 Decompression fasciotomy, leg; posterior compartment(s) only, with debridement of nonviable",
                "27894 Decompression fasciotomy, leg; anterior and/or lateral, and posterior compartment(s), with debridement of nonviable muscle and/or nerve",
                "28035 Release, tarsal tunnel (posterior tibial nerve decompression)",
                "28080 Excision, interdigital (Morton) neuroma, single, each",
                "28090 Excision of lesion, tendon, tendon sheath, or capsule (including synovectomy) (eg, cyst or ganglion);",
                "28092 Excision of lesion, tendon, tendon sheath, or capsule (including synovectomy) (eg, cyst or ganglion);",
                "28110 Ostectomy, partial excision, fifth metatarsal head (bunionette) (separate procedure)",
                "28116 Ostectomy, excision of tarsal coalition",
                "28118 Ostectomy, calcaneus;",
                "28119 Ostectomy, calcaneus; for spur, with or without plantar fascial release",
                "28190 Removal of foreign body, foot; subcutaneous",
                "28192 Removal of foreign body, foot; deep",
                "28193 Removal of foreign body, foot; complicated",
                "28288 Ostectomy, partial, exostectomy or condylectomy, metatarsal head, each metatarsal head",
                "28289 Hallux rigidus correction with cheilectomy, debridement and capsular release of the first",
                "28315 Sesamoidectomy, first toe (separate procedure)",
                "28400 Closed treatment of calcaneal fracture; without manipulation",
                "28405 Closed treatment of calcaneal fracture; with manipulation",
                "28406 Percutaneous skeletal fixation of calcaneal fracture, with manipulation",
                "28415 Open treatment of calcaneal fracture, with or without internal or external fixation;",
                "28420 Open treatment of calcaneal fracture, with or without internal or external fixation; with primary iliac or other autogenous bone graft (includes obtaining graft)",
                "28430 Closed treatment of talus fracture; without manipulation",
                "28435 Closed treatment of talus fracture; with manipulation",
                "28436 Percutaneous skeletal fixation of talus fracture, with manipulation",
                "28445 Open treatment of talus fracture, with or without internal or external fixation",
                "28450 Treatment of tarsal bone fracture (except talus and calcaneus); without manipulation, each",
                "28455 Treatment of tarsal bone fracture (except talus and calcaneus); with manipulation, each",
                "28456 Percutaneous skeletal fixation of tarsal bone fracture (except talus and calcaneus), with",
                "28465 Open treatment of tarsal bone fracture (except talus and calcaneus), with or without internal or",
                "28470 Closed treatment of metatarsal fracture; without manipulation, each",
                "28475 Closed treatment of metatarsal fracture; with manipulation, each",
                "28476 Percutaneous skeletal fixation of metatarsal fracture, with manipulation, each",
                "28485 Open treatment of metatarsal fracture, with or without internal or external fixation, each",
                "28490 Closed treatment of fracture great toe, phalanx or phalanges; without manipulation",
                "28495 Closed treatment of fracture great toe, phalanx or phalanges; with manipulation",
                "28496 Percutaneous skeletal fixation of fracture great toe, phalanx or phalanges, with manipulation",
                "28505 Open treatment of fracture great toe, phalanx or phalanges, with or without internal or external",
                "28510 Closed treatment of fracture, phalanx or phalanges, other than great toe; without manipulation, each",
                "28515 Closed treatment of fracture, phalanx or phalanges, other than great toe; with manipulation, each",
                "28525 Open treatment of fracture, phalanx or phalanges, other than great toe, with or without internal or",
                "28530 Closed treatment of sesamoid fracture",
                "28531 Open treatment of sesamoid fracture, with or without internal fixation",
                "28540 Closed treatment of tarsal bone dislocation, other than talotarsal; without anesthesia",
                "28545 Closed treatment of tarsal bone dislocation, other than talotarsal; requiring anesthesia",
                "28546 Percutaneous skeletal fixation of tarsal bone dislocation, other than talotarsal, with manipulation",
                "28555 Open treatment of tarsal bone dislocation, with or without internal or external fixation",
                "28570 Closed treatment of talotarsal joint dislocation; without anesthesia",
                "28575 Closed treatment of talotarsal joint dislocation; requiring anesthesia",
                "28576 Percutaneous skeletal fixation of talotarsal joint dislocation, with manipulation",
                "28585 Open treatment of talotarsal joint dislocation, with or without internal or external fixation",
                "28600 Closed treatment of tarsometatarsal joint dislocation; without anesthesia",
                "28605 Closed treatment of tarsometatarsal joint dislocation; requiring anesthesia",
                "28606 Percutaneous skeletal fixation of tarsometatarsal joint dislocation, with manipulation",
                "28615 Open treatment of tarsometatarsal joint dislocation, with or without internal or external fixation",
                "28630 Closed treatment of metatarsophalangeal joint dislocation; without anesthesia",
                "28635 Closed treatment of metatarsophalangeal joint dislocation; requiring anesthesia",
                "28636 Percutaneous skeletal fixation of metatarsophalangeal joint dislocation, with manipulation",
                "28645 Open treatment of metatarsophalangeal joint dislocation, with or without internal or external fixation",
                "28660 Closed treatment of interphalangeal joint dislocation; without anesthesia",
                "28665 Closed treatment of interphalangeal joint dislocation; requiring anesthesia",
                "28666 Percutaneous skeletal fixation of interphalangeal joint dislocation, with manipulation",
                "28675 Open treatment of interphalangeal joint dislocation, with or without internal or external fixation",
                "29805 Arthroscopy, shoulder, diagnostic, with or without synovial biopsy (separate procedure)",
                "29806 Arthroscopy, shoulder, surgical; capsulorrhaphy",
                "29807 Arthroscopy, shoulder, surgical; repair of SLAP lesion",
                "29819 Arthroscopy, shoulder, surgical; with removal of loose body or foreign body",
                "29820 Arthroscopy, shoulder, surgical; synovectomy, partial",
                "29821 Arthroscopy, shoulder, surgical; synovectomy, complete",
                "29822 Arthroscopy, shoulder, surgical; debridement, limited",
                "29823 Arthroscopy, shoulder, surgical; debridement, extensive",
                "29824 Arthroscopy, shoulder, surgical; distal claviculectomy including distal articular surface (Mumford",
                "29825 Arthroscopy, shoulder, surgical; with lysis and resection of adhesions, with or without manipulation",
                "29826 Arthroscopy, shoulder, surgical; decompression of subacromial space with partial acromioplasty, with or without coracoacromial release",
                "29827 Arthroscopy, shoulder, surgical; with rotator cuff repair",
                "29828 Treatment for arthroscopic surgical biceps tenodesis",
                "29830 Arthroscopy, elbow, diagnostic, with or without synovial biopsy (separate procedure)",
                "29834 Arthroscopy, elbow, surgical; with removal of loose body or foreign body",
                "29835 Arthroscopy, elbow, surgical; synovectomy, partial",
                "29836 Arthroscopy, elbow, surgical; synovectomy, complete",
                "29837 Arthroscopy, elbow, surgical; debridement, limited",
                "29838 Arthroscopy, elbow, surgical; debridement, extensive",
                "29844 Arthroscopy, wrist, surgical; synovectomy, partial",
                "29845 Arthroscopy, wrist, surgical; synovectomy, complete",
                "29846 Arthroscopy, wrist, surgical; excision and/or repair of triangular fibrocartilage and/or joint",
                "29847 Arthroscopy, wrist, surgical; internal fixation for fracture or instability",
                "29848 Endoscopy, wrist, surgical, with release of transverse carpal ligament",
                "29850 Arthroscopically aided treatment of intercondylar spine(s) and/or tuberosity fracture(s) of the knee, with or without manipulation; without internal or external fixation (includes arthroscopy)",
                "29851 Arthroscopically aided treatment of intercondylar spine(s) and/or tuberosity fracture(s) of the knee, with or without manipulation; with internal or external fixation (includes arthroscopy)",
                "29855 Arthroscopically aided treatment of tibial fracture, proximal (plateau); unicondylar, with or without internal or external fixation (includes arthroscopy)",
                "29856 Arthroscopically aided treatment of tibial fracture, proximal (plateau); bicondylar, with or without internal or external fixation (includes arthroscopy)",
                "29860 Arthroscopy, hip, diagnostic with or without synovial biopsy (separate procedure)",
                "29861 Arthroscopy, hip, surgical; with removal of loose body or foreign body",
                "29862 Arthroscopy, hip, surgical; with debridement/shaving of articular cartilage (chondroplasty), abrasion arthroplasty, and/or resection of labrum",
                "29863 Arthroscopy, hip, surgical; with synovectomy",
                "29866 Arthroscopy, knee, surgical; osteochondral autograft(s) (eg, mosaicplasty) (includes harvesting of",
                "29867 Arthroscopy, knee, surgical; osteochondral allograft (eg, mosaicplasty)",
                "29868 Arthroscopy, knee, surgical; meniscal transplantation (includes arthrotomy for meniscal insertion),",
                "29870 Arthroscopy, knee, diagnostic, with or without synovial biopsy (separate procedure)",
                "29871 Arthroscopy, knee, surgical; for infection, lavage and drainage",
                "29873 Arthroscopy, knee, surgical; with lateral release",
                "29874 Arthroscopy, knee, surgical; for removal of loose body or foreign body (eg, osteochondritis dissecans fragmentation, chondral fragmentation)",
                "29875 Arthroscopy, knee, surgical; synovectomy, limited (eg, plica or shelf resection) (separate procedure)",
                "29876 Arthroscopy, knee, surgical; synovectomy, major, two or more compartments (eg, medial or lateral)",
                "29877 Arthroscopy, knee, surgical; debridement/shaving of articular cartilage (chondroplasty)",
                "29879 Arthroscopy, knee, surgical; abrasion arthroplasty (includes chondroplasty where necessary) or",
                "29880 Arthroscopy, knee, surgical; with meniscectomy (medial AND lateral, including any meniscal",
                "29881 Arthroscopy, knee, surgical; with meniscectomy (medial OR lateral, including any meniscal shaving)",
                "29882 Arthroscopy, knee, surgical; with meniscus repair (medial OR lateral)",
                "29883 Arthroscopy, knee, surgical; with meniscus repair (medial AND lateral)",
                "29884 Arthroscopy, knee, surgical; with lysis of adhesions, with or without manipulation (separate",
                "29885 Arthroscopy, knee, surgical; drilling for osteochondritis dissecans with bone grafting, with or without internal fixation (including debridement of base of lesion)",
                "29886 Arthroscopy, knee, surgical; drilling for intact osteochondritis dissecans lesion",
                "29887 Arthroscopy, knee, surgical; drilling for intact osteochondritis dissecans lesion with internal fixation",
                "29888 Arthroscopically aided anterior cruciate ligament repair/augmentation or reconstruction",
                "29889 Arthroscopically aided posterior cruciate ligament repair/augmentation or reconstruction",
                "29891 Arthroscopy, ankle, surgical, excision of osteochondral defect of talus and/or tibia, including drilling",
                "29892 Arthroscopically aided repair of large osteochondritis dissecans lesion, talar dome fracture, or tibial plafond fracture, with or without internal fixation (includes arthroscopy)",
                "29893 Endoscopic plantar fasciotomy",
                "29894 Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; with removal of loose body or foreign",
                "29895 Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; synovectomy, partial",
                "29897 Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; debridement, limited",
                "29898 Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; debridement, extensive",
                "29899 Arthroscopy, ankle (tibiotalar and fibulotalar joints), surgical; with ankle arthrodesis",
                "64718 Neuroplasty and/or transposition; ulnar nerve at elbow",
                "64719 Neuroplasty and/or transposition; ulnar nerve at wrist",
                "64721 Neuroplasty and/or transposition; median nerve at carpal tunnel"
            ]
        },
        {
            active: true,
            department: "ENT" ,
            modalities: ["CT", "US", "VL"],
            reasons: [
                "Infection Ear, Left", "Infection Ear, Right", "Sore Throat",
                "Sinus infection"
            ]
        },
    ]
};

module.exports = appConfig;